[package]
name = "pass-rofi-gui"
description = "A password manager GUI that integrates pass with rofi"
version = "1.0.1"
authors = ["alecdwm <alec@owls.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0.17"
libreauth = "0.11.0"
notify-rust = "3.5.0"
structopt = "0.2.14"
