[package]
name = "pass-rofi-gui"
description = "A rofi GUI for pass"
version = "0.1.0"
authors = ["alecdwm <alec@owls.io>"]
edition = "2018"

[dependencies]
structopt = "0.2.14"
failure = "0.1.5"
boringauth = "0.7.0"
