[package]
name = "pass-rofi-gui"
description = "A password manager GUI that integrates pass with rofi"
version = "1.0.2"
authors = ["alecdwm <alec@owls.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0.27"
miniotp = "1.1.0"
notify-rust = "3.6.3"
structopt = "0.3.11"
